name: "Configure t_config.py file"
author: Luke Swanson
description: "Given a set of appropriate inputs, this action prepares the t_config.py file for running the ogd-logger testbeds."
branding:
  icon: 'clipboard'
  color: 'blue'
inputs:
  verbose_output:
    description: "Whether to output extra debugging lines from tests."
    required: false
    default: "False"
  with_log:
    description: "Whether to run the log.php tests."
    required: false
    default: "False"
  with_register:
    description: "Whether to run the register.php tests."
    required: false
    default: "False"
  remote_url:
    description: "The URL for calls to a remote instance of the Hello API"
    required: False
    default: "127.0.0.1:5000"
  config_path:
    description: "Local path to test config folder"
    required: false
    default: 'tests/config'
  app_branch:
    description: "The name to use for app_branch in the test events"
    required: false
    default: 'main'

runs:
  using: "composite"
  steps:
    - name: Set up config
      run: cp ${{ inputs.config_path }}/t_config.py.template ${{ inputs.config_path }}/t_config.py 
      shell: bash
    - name: Set Output Verbosity
      run: sed -i 's@"VERBOSE"\s*:\s*False@"VERBOSE":${{ inputs.verbose_output }}@g' ${{ inputs.config_path }}/t_config.py
      shell: bash
    - name: Set log.php test to run or not
      run: sed -i 's@"LOG"\s*:\s*True@"LOG":${{ inputs.with_log }}@g'                ${{ inputs.config_path }}/t_config.py
      shell: bash
    - name: Set register.php test to run or not
      run: sed -i 's@"REGISTER"\s*:\s*True@"REGISTER":${{ inputs.with_register }}@g' ${{ inputs.config_path }}/t_config.py
      shell: bash
    - name: Set Remote URL
      run: sed -i 's@"address_placeholder"@"${{ inputs.remote_url }}"@g'             ${{ inputs.config_path }}/t_config.py
      shell: bash
    - name: Set App Branch
      run: sed -i 's@"branch_placeholder"@"${{ inputs.app_branch }}"@g'              ${{ inputs.config_path }}/t_config.py
      shell: bash
