name: "Set up config file for a run"
author: Luke Swanson
description: "Given a set of appropriate inputs, this action prepares a config.js file for the Website API."
branding:
  icon: 'clipboard'
  color: 'blue'
inputs:
  db_host:
    description: "Host of the database"
    required: false
    default: '127.0.0.1'
  db_user:
    description: "User name for the database"
    required: true
    default: 'user placeholder'
  db_pass:
    description: "Password for the database"
    required: true
    default: 'pass placeholder'
  db_name:
    description: "Name of the database to use"
    required: false
    default: 'opengamedata'
  version_name:
    description: "Name of version to send from this instance of logger"
    required: true
    default: 'UNKNOWN VERSION'
  monitor_enabled:
    description: "Whether to enable sending messages to monitor API at all"
    required: false
    default: 'true'
  monitor_url:
    description: "URL for the monitor API"
    required: true
    default: 'monitor placeholder'
  monitor_timeout:
    description: "How long the logger should wait for a response after sending data to the monitor API"
    required: false
    default: '1'

runs:
  using: "composite"
  steps:
    - name: Set up config
      run: cp src/config.php.template src/config.php 
      shell: bash
    - name: Set DB hostname
      run: sed -i 's@127.0.0.1@${{ inputs.db_host }}@g' src/config.php
      shell: bash
    - name: Set DB username
      run: sed -i 's@user placeholder@${{ inputs.db_user }}@g' src/config.php
      shell: bash
    - name: Set DB pass
      run: sed -i 's@pass placeholder@${{ inputs.db_pass }}@g' src/config.php
      shell: bash
    - name: Set DB name
      run: sed -i 's@db placeholder@${{ inputs.db_name }}@g' src/config.php
      shell: bash
    - name: Set version name
      run: sed -i 's@version placeholder@${{ inputs.version_name }}@g' src/config.php
      shell: bash
    - name: Enable/disable monitor API
      run: sed -i 's@monitorEnabled = true@monitorEnabled = ${{inputs.monitor_enabled}}@g' src/config.php
      shell: bash
    - name: Set monitor API location
      run: sed -i 's@monitor placeholder@${{inputs.monitor_url}}@g' src/config.php
      shell: bash
    - name: Set monitor API timeout
      run: sed -i 's@monitorTimeout = 1@monitorTimeout = ${{inputs.monitor_timeout}}@g' src/config.php
      shell: bash
