name: "Set up config file for a run"
author: Luke Swanson
description: "Given a set of appropriate inputs, this action prepares a config.js file for the Website API."
branding:
  icon: 'clipboard'
  color: 'blue'
inputs:
  db_host:
    description: "Host of the database"
    required: false
    default: '127.0.0.1'
  db_user:
    description: "User name for the database"
    required: true
    default: 'user placeholder'
  db_pass:
    description: "Password for the database"
    required: true
    default: 'pass placeholder'
  db_name:
    description: "Name of the database to use"
    required: false
    default: 'opengamedata'

runs:
  using: "composite"
  steps:
    - name: Set up config
      run: cp config.php.template config.php 
      shell: bash
    - name: Set DB hostname
      run: sed -i 's@127.0.0.1@${{inputs.db_host}}@g' config.php
      shell: bash
    - name: Set DB username
      run: sed -i 's@user placeholder@${{inputs.db_user}}@g' config.php
      shell: bash
    - name: Set DB pass
      run: sed -i 's@pass placeholder@${{inputs.db_pass}}@g' config.php
      shell: bash
    - name: Set DB name
      run: sed -i 's@db placeholder@${{inputs.db_name}}@g' config.php
      shell: bash